# Generated by Django 3.2.23 on 2024-01-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_picture',
            field=models.ImageField(blank=True, upload_to='userprofile'),
        ),
    ]
