# Generated by Django 3.2.23 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_default_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
