# Generated by Django 3.2.23 on 2024-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.CharField(choices=[('order', 'Order Query'), ('general', 'General Query')], default='query', max_length=20),
        ),
    ]
