# Generated by Django 3.2.23 on 2024-02-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20240202_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_surname',
        ),
    ]
