# Generated by Django 3.2.23 on 2024-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
