# Generated by Django 3.2.23 on 2023-12-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231222_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='include',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
