# Generated by Django 3.2.23 on 2024-01-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='include',
            field=models.CharField(blank=True, default=False, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_was',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=6, null=True),
        ),
    ]
