# Generated by Django 3.2.23 on 2024-02-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_giftwrap',
        ),
    ]
