# Generated by Django 3.2.23 on 2024-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_has_sizes_product_has_giftwrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
    ]
