# Generated by Django 3.2.23 on 2024-02-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_description_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='product_rating',
        ),
    ]
