# Generated by Django 3.2.23 on 2024-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20240329_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genders',
            old_name='friendly_name',
            new_name='gender_friendly_name',
        ),
    ]
